language: ruby
os: osx
env:
  - FF_VERSION=52-2-1
  - FF_VERSION=76-4-4
  - FF_VERSION=45-0-2

script:
  - "brew cask install Casks/firefox-esr-$FF_VERSION.rb"
  - "brew cask uninstall firefox-esr-$FF_VERSION"

