language: ruby
os: osx
env:
  - FF_VERSION=52-2-1
  - FF_VERSION=52-2-0
  - FF_VERSION=52-1-0
  - FF_VERSION=52-0-2
  - FF_VERSION=52-0
  - FF_VERSION=45-7-0
  - FF_VERSION=45-6-0
  - FF_VERSION=45-5-1
  - FF_VERSION=45-5-0
  - FF_VERSION=45-4-0
  - FF_VERSION=45-3-0
  - FF_VERSION=45-2-0
  - FF_VERSION=45-1-0
  - FF_VERSION=45-0-2
  - FF_VERSION=45-0-1
  - FF_VERSION=45-0
  - FF_VERSION=38-6-1
  - FF_VERSION=38-6-0
  - FF_VERSION=38-5-2
  - FF_VERSION=38-5-1
  - FF_VERSION=38-5-0
  - FF_VERSION=38-4-0
  - FF_VERSION=38-3-0
  - FF_VERSION=38-2-1
  - FF_VERSION=38-2-0
  - FF_VERSION=38-0-1
  - FF_VERSION=38-0
  - FF_VERSION=31-6-0
  - FF_VERSION=31-5-3
  - FF_VERSION=31-5-0
  - FF_VERSION=45-0-2

script:
  - "brew audit Casks/firefox-esr-$FF_VERSION.rb"
  - "brew style Casks/firefox-esr-$FF_VERSION.rb"
  - "brew cask install Casks/firefox-esr-$FF_VERSION.rb"
  - "brew cask uninstall firefox-esr-$FF_VERSION"
